#!/bin/dash

if [ $# -ne 1 ]; then
    echo "usage: $0 <branch>"
    exit 1
fi
if [ ! -d ".tigger/branches/$1" ]; then
    echo "$0: error: unkown branch $1"
    exit 1
fi
echo $1>".tigger/current_branch"